# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='id',
            new_name='mentor_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='unique_id',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='job',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Entry level (0-2 yrs)', 'Entry level (0-2 yrs)'), ('Mid level (2+ yrs)', 'Mid level (2+ yrs)'), ('Manager', 'Manager'), ('Executive', 'Executive'), ('Not Applicable', 'Not Applicable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Below High School', 'Below High School'), ('High School', 'High School'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree'), ('Doctrate Degree', 'Doctrate Degree')], max_length=40, null=True),
        ),
    ]
