# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='enroll_id',
        ),
        migrations.AddField(
            model_name='score',
            name='progress',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
