# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/epsilon/'),
        ),
    ]
