# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0002_auto_20180327_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='has',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
