# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0002_auto_20180328_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
    ]
