# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0003_auto_20180328_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='option_a',
        ),
        migrations.AddField(
            model_name='option',
            name='option_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
