# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0002_auto_20180328_1035'),
        ('epsilon', '0004_auto_20180328_0956'),
    ]

    operations = [
    ]
