# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0004_auto_20180328_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=20),
        ),
    ]
