# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0005_merge_20180328_1828'),
        ('epsilon', '0005_auto_20180329_0341'),
    ]

    operations = [
    ]
