# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0006_merge_20180330_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_e',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
