# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0007_auto_20180330_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='career_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epsilon.Career'),
        ),
    ]
